name: simulasi_ukk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^9.1.0
  customer_repository:
    path: packages/customer_repository
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  formz: ^0.8.0
  product_repository:
    path: packages/product_repository
  supabase_flutter: ^2.10.3
  url_strategy: ^0.3.0
  user_repository:
    path: packages/user_repository
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
